module.exports = {
    'btc' : 'Bitcoin',
    'ltc' : 'Litecoin',
    'eth' : 'Ethereum',
    'bch' : 'Bitcoin Cash',
    'xrp' : 'Ripple',
    'neo' : 'Neo',
    'xmr' : 'Monero',
    'etc' : 'Ethereum Classic',
    'qtum' : 'QTUM',
    'zec' : 'ZCash',
    'xem' : 'Nem',
    'dash' : 'Dash',
    'btg' : 'Bitcoin Gold',
    'dgb' : 'DigiByte',
    'gnt' : 'Golem Network Token',
    'strat' : 'Stratis',
    'steem' : 'Steem',
    'rep' : 'Augur',
    'lsk' : 'Lisk',
    'fct' : 'Factoids',
    'pivx' : 'PIVX',
    'cloak' : 'CloakCoin',
    'nxt' : 'NXT',
    'doge' : 'Doge Coin',
    'cvc' : 'Civic',
    'sc' : 'SiaCoin',
    'pay' : 'TenX',
    'ark' : 'Ark',
    'bcc' : 'BitConnect Coin',
    'omg' : 'OmiseGo',
    'bat' : 'Basic Attention Token',
    'bts' : 'Bitshares',
    'dcn' : 'Dentacoin',
    'zil' : 'Zilliqa',
    'zrx': '0x',

};